[package]
org = "ballerina"
name = "grpc_tests"
version = "1.5.0"

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-1.5.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.5.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2201.3.0-rc1-20221019-113600-76ade83d.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.20.3.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2201.3.0-rc1-20221019-113600-76ade83d.jar"
